### ISSUE TITLE
panic: invalid character ',' after object key

### ISSUE THREAD

**Issue by algent-al** [cooperspencer/uas#2]
$ uas firefox
Searching for firefox
panic: invalid character ',' after object key

goroutine 1 [running]:
main.main()
	/home/andy/go/src/uas/main.go:219 +0x27a0

**Comment by cooperspencer** [comment]
Just tried that. For now it seems to be working. That's a problem with the json it checks out from another repository. I will add a check after I downloaded everything from the api's, so that this problem won't happen again.

**Comment by cooperspencer** [comment]
I added a procedure to check if uas understands the json before uploading it to the repo
