### ISSUE TITLE
Update Apps

### ISSUE THREAD

**Issue by cooperspencer** [cooperspencer/uas#3]
find a way to update installed images.

**Comment by algent-al** [comment]
```
$ whereis firefox
firefox: /usr/bin/firefox /usr/lib64/firefox /snap/bin/firefox
```

I have installed firefox from repo and from snap to test this.
If there is a snap package then there it should be on `/snap/bin/firefox`

or `snap list | grep firefox` seems it is possible what are you trying to do.

**Comment by cooperspencer** [comment]
yes, that's ok so far. This issue is for a parameter like '-u' to update every package installed per Snap, Flatpak and AppImage. Snap and Flatpak are easy to accomplish. AppImage might be a bit tricky but I already have an idea how to do it.

**Comment by cooperspencer** [comment]
added.
