### ISSUE TITLE
Adding quit option - Feature request

### ISSUE THREAD

**Issue by algent-al** [cooperspencer/uas#4]
I think maybe is good to have a quit function.
![uas-feature](https://user-images.githubusercontent.com/46356616/59411601-ef051800-8dbb-11e9-938b-0855d14c93ab.png)
For example replace "0" not with first flathub entry, but with "quit", and then the numbering of altenatives can be start from "1". In this case (with VLC search) if a choose third option of apps, I can press 3 instead of 2.

If not possible, Then replace the last sentence "Select the number you'd like:" with "Select the number you'd like, or q to quit:".

**Comment by cooperspencer** [comment]
Sure that's not much of a deal. I could let the numbering start at 1 and add the 'q' for quitting.
Does that sound good for you?

**Comment by algent-al** [comment]
Yes, that is fine. Starting from 1 is more natyral.

**Comment by cooperspencer** [comment]
should be done now.
